# Site settings
title: Historia Data
description: Una definición sencilla que contiene elementos muy complejos. La historia digital es un método de investigación que utiliza recursos digitales para construir explicaciones históricas. Los recursos que emplea son principalmente datos digitales y programas informáticos dedicados a la minería de datos. Este laboratorio digital —en forma de entradas de blog— es el esfuerzo inicial de un grupo de jóvenes académicos latinoamericanos que quieren comprender y evaluar las ventajas y los límites en la aplicación de estas tecnologías al campo de la historia, las ciencias sociales y las humanidades.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Historia Data
user_description: Una definición sencilla que contiene elementos muy complejos. La historia digital es un método de investigación que utiliza recursos digitales para construir explicaciones históricas. Los recursos que emplea son principalmente datos digitales y programas informáticos dedicados a la minería de datos. Este laboratorio digital —en forma de entradas de blog— es el esfuerzo inicial de un grupo de jóvenes académicos latinoamericanos que quieren comprender y evaluar las ventajas y los límites en la aplicación de estas tecnologías al campo de la historia, las ciencias sociales y las humanidades.
user_title: Laboratorio de historia digital
email: davidcc86@gmail.com
twitter_username: davidchavarria_
github_username: david-chavarria

# Google-analytics
google-analytics:
  id: "125430488"

exclude: ['package.json', 'src' , 'node_modules']
