# Site settings
title: Historia+Data
description: La historia digital es un método de investigación que utiliza recursos digitales para construir explicaciones históricas. Los principales recursos empleados son datos digitales y programas informáticos dedicados a la minería de datos. 

La filosofía de este laboratorio digital —en forma de entradas de blog— es un esfuerzo inicial por comprender y evaluar las enormes ventajas y las grandes limitaciones que resultan de la aplicación de estas tecnologías al campo de la historia, las ciencias sociales y las humanidades.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Historia+Data
user_description: La historia digital es un método de investigación que utiliza recursos digitales para construir explicaciones históricas. Los principales recursos empleados son datos digitales y programas informáticos dedicados a la minería de datos.

La filosofía de este laboratorio digital —en forma de entradas de blog— es un esfuerzo inicial por comprender y evaluar las enormes ventajas y las grandes limitaciones que resultan de la aplicación de estas tecnologías al campo de la historia, las ciencias sociales y las humanidades.
user_title: Blog de historia digital
email: davidcc86@gmail.com
twitter_username: davidchavarria_
github_username: david-chavarria
gplus_username: +DavidChavarr%C3%ADaCamacho

# Google-analytics
google-analytics:
  id: "125430488"

exclude: ['package.json', 'src' , 'node_modules']
