# Site settings
title: Historia+Data
description: La historia digital utiliza métodos de investigación digital para examinar y representar el pasado mediante el uso de las tecnologías de la información y la comunicación.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Historia+Data
user_description: La historia digital utiliza métodos de investigación digital para examinar y representar el pasado mediante el uso de las tecnologías de la información y la comunicación.
user_title: Blog de historia digital
email: davidcc86@gmail.com
twitter_username: davidchavarria_
github_username: david-chavarria
gplus_username: +DavidChavarr%C3%ADaCamacho

# Google-analytics
google-analytics:
  id: "125430488"

exclude: ['package.json', 'src' , 'node_modules']
