# Site settings
title: chavarria.science
description: Diseño y edición de textos académicos
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: chavarria.science
user_description: Editor, docente e investigador
user_title: Diseño y edición de textos académicos
email: davidcc86@gmail.com
twitter_username: davidchavarria_
github_username: david-chavarria

# Google-analytics
google-analytics:
  id: "125430488"

exclude: ['package.json', 'src' , 'node_modules']
